package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

public class Borrow extends javax.swing.JInternalFrame {

    Connection conn=null;
    PreparedStatement pstmt=null;
    ResultSet rs=null;
    
    public Borrow() {
        initComponents();
        conn=DBConnect.connect();
        autoid();
       
        
     setting_date();
     table_l();
    }
    
    private void setting_date()
    {
        int no_of_ret_days=10;
        LocalDate today=LocalDate.now();
        LocalDate rdate=today.plus(no_of_ret_days,ChronoUnit.DAYS);
        txtidate.setText(today.toString());
        txtrdate.setText(rdate.toString());
    }
    
    private void clear()
    {
    txtbid.setText("");
    txtmid.setText("");
    txtbname.setText("");
    txtmname.setText("");
    cmbmtype.setSelectedIndex(0);
    cmbbtype.setSelectedIndex(0);
    }
    
    
        private void autoid()
    {
        
        try{
            String que="SELECT `recno` FROM `BookLend` ORDER  BY recno DESC LIMIT 1";
            //SELECT `recno`, `mid`, `bid`, `issuedate`, `returndate` FROM `BookLend` WHERE 1
            pstmt=(PreparedStatement) conn.prepareStatement(que);
            rs = pstmt.executeQuery();
            if(rs.next())
            {
                String rnno=rs.getString("recno");
                int co=rnno.length();
                String txt=rnno.substring(0,2);
                String num=rnno.substring(2,co);
                int n=Integer.parseInt(num);
                n++;
                String snum=Integer.toString(n);
                String ftxt=txt+snum;
                txtrecno.setText(ftxt);
            }
            else
                txtrecno.setText("RN1");
           }
       catch(Exception e)
          {
              System.out.println("from the borrow book class thers is a problem in autoid method "+e);
          }
    }
        
   private void table_l()
    {
        try
        {
            String s="SELECT  `mid`, `bid`, `issuedate`, `returndate` FROM `booklend` WHERE `recno`='"+txtrecno.getText()+"'";
            pstmt=(PreparedStatement)conn.prepareStatement(s);
            rs=pstmt.executeQuery();
          detailtable.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
          System.out.println("from add book issue class and table_l method the data is fetch and placed in table ");
        }
        catch(Exception e)
        { System.out.println("from borrow class and table_l method facing prob "+e);
        }
    }
   
   private void update()
   {
     try
     {
         
         String sql="UPDATE `books` SET  `mark`='1' WHERE bid='"+txtbid.getText()+"'";
         pstmt=(PreparedStatement)conn.prepareStatement(sql);
         pstmt.execute();
         table_l();
     }
     catch(Exception e)
     {
         System.out.println("from borrow class and update method facing prob "+e);
     }
   
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbbtype = new javax.swing.JComboBox();
        cmbmtype = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        btnissue = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtbname = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        txtidate = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        btnclear = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtrecno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtrdate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailtable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbbtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Borrow", "Read Only" }));
        jPanel1.add(cmbbtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 130, 30));

        cmbmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Type", "Student", "Other" }));
        jPanel1.add(cmbmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel16.setText("BOOK LEND");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 9, 200, 30));

        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, 30));

        btnissue.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnissue.setText("ISSUE");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });
        jPanel1.add(btnissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 160, 50));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel14.setText("Issue Date");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 30));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel10.setText("Member Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel1.add(txtbname, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 130, 30));

        txtmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmidKeyReleased(evt);
            }
        });
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));

        txtidate.setEditable(false);
        jPanel1.add(txtidate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 140, 30));
        jPanel1.add(txtmname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 130, 30));

        btnclear.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 160, 50));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel12.setText("Book Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        txtrecno.setEditable(false);
        txtrecno.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jPanel1.add(txtrecno, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 160, 50));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel15.setText("Return Date");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, 30));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel9.setText("Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel11.setText("Book ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel8.setText("Member ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel13.setText("Book Type");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        txtrdate.setEditable(false);
        jPanel1.add(txtrdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 140, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 320, 200));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 330, 200));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 210, 260));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 660, 50));

        detailtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(detailtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 337, 900, 140));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 900, 280));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 30));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmidKeyReleased
       try{
            String que="SELECT  `name`,`type` FROM `members` WHERE `mid`='"+txtmid.getText()+"'";
            pstmt=(PreparedStatement) conn.prepareStatement(que);
            rs = pstmt.executeQuery();
           
            if(rs.next())
            {
               txtmname.setText(rs.getString("name"));
               cmbmtype.setSelectedItem(rs.getString("type"));
            }
            else
            {
                txtmname.setText("");
                cmbmtype.setSelectedIndex(0);
            }
           }
       catch(Exception e)
          {
              System.out.println("from the borrow class thers is a problem in fetching member id data "+e);
          }
    }//GEN-LAST:event_txtmidKeyReleased

    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
          try{
            String que="SELECT  `name`,`book_type` FROM `Books` WHERE `bid`='"+txtbid.getText()+"'";
            pstmt=(PreparedStatement) conn.prepareStatement(que);
            rs = pstmt.executeQuery();
           
            if(rs.next())
            {
               txtbname.setText(rs.getString("name"));
               System.out.println(rs.getString("book_type"));
               cmbbtype.setSelectedItem(rs.getString("book_type"));
            }
            else
            {
              txtbname.setText("");
              cmbbtype.setSelectedIndex(0);
            }
           }
       catch(Exception e)
          {
              System.out.println("from the borrow class thers is a problem in fetching book id data "+e);
          }
    }//GEN-LAST:event_txtbidKeyReleased

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
       String mid,bid,idate,rdate,recno;
       recno=txtrecno.getText();
       mid=txtmid.getText();
       bid=txtbid.getText();
       idate=txtidate.getText();
       rdate=txtrdate.getText();
       
       try
       {
           String que="INSERT INTO `booklend`(`recno`, `mid`, `bid`, `issuedate`, `returndate`,`mark`) VALUES ('"+recno+"','"+mid+"','"+bid+"','"+idate+"','"+rdate+"','0')";
            pstmt=(PreparedStatement) conn.prepareStatement(que);
            pstmt.execute();
           JOptionPane.showMessageDialog(this,"data is successfully added");
           update(); 
           table_l();
           clear();
       }
       catch(Exception e)
       {
       System.out.println("from Borrow class and issue method we are hacing trouble in entering data "+e);
       }
       
       
       
       
       
       
    }//GEN-LAST:event_btnissueActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       clear();
    }//GEN-LAST:event_btnclearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnissue;
    private javax.swing.JComboBox cmbbtype;
    private javax.swing.JComboBox cmbmtype;
    private javax.swing.JTable detailtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtbname;
    private javax.swing.JTextField txtidate;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtrdate;
    private javax.swing.JTextField txtrecno;
    // End of variables declaration//GEN-END:variables
}
