package Interface;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Return extends javax.swing.JInternalFrame {

    Connection conn=null;
    PreparedStatement pstmt=null;
    ResultSet rs=null;
         
    public Return() 
    {
        initComponents();
        conn=DBConnect.connect();
    }
    
    
  private void update()
   {
     try
     {
         
         String sql="UPDATE `books` SET  `mark`='0' WHERE bid='"+txtbid.getText()+"'";
         pstmt=(PreparedStatement)conn.prepareStatement(sql);
         pstmt.execute();
         System.out.println("the books table is updtaed ");
     }
     catch(Exception e)
     {
         System.out.println("from return class and update method facing prob "+e);
     }
   
   }
  
    private void returnbook()
   {
     try
     {
         
         String sql="UPDATE `booklend` SET  `mark`='1' WHERE bid='"+txtbid.getText()+"'";
         pstmt=(PreparedStatement)conn.prepareStatement(sql);
         pstmt.execute();
         System.out.println("the booklend  table is updtaed ");
     }
     catch(Exception e)
     {
         System.out.println("from return class and update method facing prob "+e);
     }
   
   }
  
  private void bill_calc()
  {
      txtprint.setText("===================="+"\n"+"  MNNIT LIBRARY  \n No of Late Days: "+
                        txtldays.getText()+"\n Total Amount to pay:"+txtfine.getText()+"\n=========================");
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtprint = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtmid = new javax.swing.JTextField();
        txtldays = new javax.swing.JTextField();
        txtfine = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtprint.setColumns(20);
        txtprint.setRows(5);
        jScrollPane1.setViewportView(txtprint);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 300, 290));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel6.setText("Book ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 80, 20));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel7.setText("Member ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 90, 20));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel8.setText("Late Days");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 20));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel9.setText("Fine");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, 20));

        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));
        jPanel1.add(txtmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 160, 30));
        jPanel1.add(txtldays, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, 30));

        txtfine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfineActionPerformed(evt);
            }
        });
        jPanel1.add(txtfine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 160, 30));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel10.setText("Return ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 11, 240, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 310));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 320, 310));

        btnreturn.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnreturn.setText("RETURN");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 330, 70));

        btnprint.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 320, 70));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 420));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        try {
            txtprint.print();
        } catch (PrinterException ex) {
           System.out.println("this is from return class facing problem in printing the receceipt "+ex);
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void txtfineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfineActionPerformed

    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
          try
          {
              String que="SELECT  `mid`, `returndate` FROM `booklend` WHERE `bid` ='"+txtbid.getText()+"' and mark='0'";
              pstmt=(PreparedStatement)conn.prepareStatement(que);
              rs=pstmt.executeQuery();
              
              if(rs.next())
              {
                  txtmid.setText(rs.getString("mid"));
                  String r_date=rs.getString("returndate");
                  LocalDate today=LocalDate.now();
                  LocalDate rdate=LocalDate.parse(r_date);
                  Long day_gap=ChronoUnit.DAYS.between(rdate,today);
                 
                
                 if(day_gap>0)
                 {
                   txtldays.setText(day_gap.toString());
                   long fine=10*day_gap;
                   txtfine.setText(String.valueOf(fine));
                 }
                 else
                 {
                 }
                 txtldays.setText("0");
                 txtfine.setText("0");
                 }
          }
          catch(Exception e)
          {
              
          }
          
    }//GEN-LAST:event_txtbidKeyReleased

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
       
        String bid,mid,fine,latedays;
        bid=txtbid.getText();
        mid=txtmid.getText();
        fine=txtfine.getText();
        latedays=txtldays.getText();
        try
       {
           String que="INSERT INTO `bookreturn`(`bid`, `mid`, `late_days`, `fine`) VALUES ('"+bid+"','"+mid+"','"+latedays+"','"+fine+"')";
            pstmt=(PreparedStatement) conn.prepareStatement(que);
            pstmt.execute();
           JOptionPane.showMessageDialog(this,"data is successfully added");
           update(); 
           returnbook();
           bill_calc();
//           table_l();
//           clear();
       }
       catch(Exception e)
       {
       System.out.println("from Borrow class and issue method we are hacing trouble in entering data "+e);
       }
        
        
        
    }//GEN-LAST:event_btnreturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextField txtfine;
    private javax.swing.JTextField txtldays;
    private javax.swing.JTextField txtmid;
    private javax.swing.JTextArea txtprint;
    // End of variables declaration//GEN-END:variables
}
